

import "./globals.css";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "MJ Admin",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <Sidebar />
        <div className="flex-1 p-6 bg-gray-100 min-h-screen">{children}</div>
      </body>
    </html>
  );
}

